# Site settings
title: "Juan de la Oliva | Solutions Architect Blog"
email: "juandelaoliva1@gmail.com"
description: >-
  Insights on technology, Drupal, AI, and more from Juan de la Oliva, a professional Solutions Architect based in Frankfurt.
twitter_username: username
github_username: juandelaoliva
minimal_mistakes_skin: default
search: true

# SEO Enhancements
url: "https://juandelaoliva.github.io"
baseurl: "/blog" # Leave empty for root deployment
lang: "en"
google_analytics: G-21EDP0MN6W
sitemap:
  changefreq: weekly
  priority: 1.0
  lastmod: auto

# Social sharing metadata
twitter:
  card: "summary_large_image"
  description: >-
    Exploring topics in technology, Drupal, AI, and more with Juan de la Oliva, an experienced Solutions Architect.
  image: "/images/juandelaoliva-juan_de_la_oliva.jpg"
  creator: "@juandelaoliva"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5 # Number of posts per page
paginate_path: /page:num/
timezone: Europe/Berlin

# Includes
include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

# Author information
author:
  name   : "Juan de la Oliva"
  avatar : "https://juandelaoliva.com/images/juandelaoliva-juan_de_la_oliva.webp"
  bio    : "Experienced Solutions Architect specializing in Drupal, AI, and web development."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://juandelaoliva.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/juan-de-la-oliva-aguilar-6324961a2/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/juandelaoliva"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/J_DLOA"

# Footer links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/juan-de-la-oliva-aguilar-6324961a2/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/juandelaoliva"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/J_DLOA"

# Default settings for posts and pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archive pages
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
